name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.17.3"
          - "1.16.3"
          - "1.15.8"
          - "1.14.5"
          - "1.13.4"
        otp:
          - "27.1"
          - "26.2"
          - "25.3"
          - "24.3"
        exclude:
          - elixir: "1.17.3"
            otp: "24.3"
          - elixir: "1.16.3"
            otp: "27.1"
          - elixir: "1.15.8"
            otp: "27.1"
          - elixir: "1.14.5"
            otp: "27.1"
          - elixir: "1.13.4"
            otp: "27.1"
          - elixir: "1.13.4"
            otp: "26.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Restore Dialyzer cache
        uses: actions/cache@v3
        with:
          path: "_build/dev/dialyxir_erlang-*_elixir-*_deps-dev.plt*"
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-dialyzer-${{ hashFiles('_build/dev/dialyxir_erlang-*_elixir-*_deps-dev.plt') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-dialyzer-
      - name: Install dependencies
        run: mix deps.get
      - name: Build (dev)
        run: mix compile
      - name: Build (test)
        run: mix compile
        with:
          mix_env: test
      - name: Run formatter
        run: mix format --check-formatted
        if: ${{ always() }}
      - name: Run tests
        run: mix test
        if: ${{ !cancelled() }}
      - name: Run credo
        run: mix credo --strict
        if: ${{ !cancelled() }}
      - name: Run gradient
        run: mix gradient
        if: ${{ !cancelled() }}
      - name: Run Dialyzer
        run: mix dialyzer
        if: ${{ !cancelled() }}
