name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --manifest-path native/crc24/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path native/crc24/Cargo.toml
      - name: Run clippy
        run: cargo clippy --manifest-path native/crc24/Cargo.toml
